module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  setupFilesAfterEnv: ['<rootDir>/tests/jest.setup.ts'],
  testMatch: ['**/tests/**/?(*.)+(spec|test).ts'],
  moduleFileExtensions: ['ts', 'js', 'json', 'node'],
  roots: [
    '<rootDir>/tests',
    '<rootDir>/app',
    '<rootDir>/repository',
    '<rootDir>/service',
    '<rootDir>/controller',
    '<rootDir>/dto',
    '<rootDir>/exception',
  ],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/$1',
    '^@app/(.*)$': '<rootDir>/app/$1',
    '^@configuration/(.*)$': '<rootDir>/configuration/$1',
    '^@controller/(.*)$': '<rootDir>/controller/$1',
    '^@repository/(.*)$': '<rootDir>/repository/$1',
    '^@utils/(.*)$': '<rootDir>/utils/$1',
    '^@config/(.*)$': '<rootDir>/configuration/$1',
    '^@dto/(.*)$': '<rootDir>/dto/$1',
    '^@service/(.*)$': '<rootDir>/service/$1',
    '^@exception/(.*)$': '<rootDir>/exception/$1',
    '^@middleware/(.*)$': '<rootDir>/middleware/$1',
    '^@common/(.*)$': '<rootDir>/common/$1',
    '^@test/(.*)$': '<rootDir>/test/$1',
    '^@prisma$': '<rootDir>/generated/prisma',
    '^@prisma/(.*)$': '<rootDir>/generated/prisma/$1',
  },
  transform: {
    '^.+\\.ts$': 'ts-jest',
  },
  collectCoverageFrom: [
    'app/**/*.ts',
    'controller/**/*.ts',
    'service/**/*.ts',
    'repository/**/*.ts',
    'middleware/**/*.ts',
    'utils/**/*.ts',
    '!**/*.d.ts',
    '!**/node_modules/**',
  ],
};
